### ISSUE TITLE
有任何疑问，这里提！！！

### ISSUE THREAD

**Issue by tracyone** [tracyone/vinux#39]
任何vim和我这个配置的问题。

**Comment by lyk7539511** [comment]
本人VIM新手, 想修改TAB键为默认4字符, 网上找了一些方法, 但是在您的vimrc中修改后并没有生效, 望不吝赐教, 谢谢.

**Comment by tracyone** [comment]
你是编辑什么文件啊，有些文件类型tab宽度被下面这个路径的文件改写了。

https://github.com/tracyone/vinux/tree/master/after/ftplugin
