### ISSUE TITLE
Does vinux will support these wonderful plugin for vim 8?

### ISSUE THREAD

**Issue by blueyi** [tracyone/vinux#43]
There are some wonderful plugins for vim8, include ale, fzf, leaderF, etc.
Will you consider to update or support these plugins for vim8?
Thanks

ps:
Donate link maybe can support PayPal.

**Comment by tracyone** [comment]
https://github.com/tracyone/vinux/wiki/config#feature-config

see this link.

For fuzzy searcher: vinux support ctrlp(default), leaderf, denite

For async lint: vinux support neomake

For complete plugin, vinux support youcompleteme, asyncomplete,deplete,supertab,clang-complete...

**Comment by tracyone** [comment]
说中文比较容易点。我这配置安装完毕的时候一半以上的功能没有使能，非常低调。然后你可以编辑~/.vim/feature.vim使能或者禁止某个特性，或者选择某个类型的插件，你可以用ctrlp来选择，看我链接里面的视频

**Comment by blueyi** [comment]
嗯嗯，感谢回复。
大概过了一下您的配置文件，之前也是在使用ctrlp，一直没用顺手，偶然间在知乎看到这个https://www.zhihu.com/question/47691414
然后就想升级一下多年的vimrc，1000多行了，感觉很乱，就想能归类，刚好搜索到了你的，非常满意，
打算定制化一下，看到最近新的一些插件，没有提供，想了解一下，是否有考虑添加这些新插件的支持
谢谢

**Comment by blueyi** [comment]
直接拉了你的配置文件用，没有什么大问题，ycm会报，valueError: still no complie flags
YCM的debug信息如下：
Printing YouCompleteMe debug information...
-- Client logfile: /tmp/ycm_qfn6hikk.log
-- Server Python interpreter: /home/blueyi/.pyenv/versions/3.6.5/bin/python
-- Server Python version: 3.6.5
-- Server has Clang support compiled in: True
-- Clang version: clang version 7.0.0 (tags/RELEASE_700/final)
-- No extra configuration file found
-- C-family completer debug information:
--   Compilation database path: None
--   Flags: []
--   Translation unit: /home/blueyi/cpp/vector_words.cpp
-- Server running at: http://127.0.0.1:46077
-- Server process ID: 24547
-- Server logfiles:
--   /tmp/ycmd_46077_stdout_1u2r07el.log
--   /tmp/ycmd_46077_stderr_nq5woc_q.log

**Comment by tracyone** [comment]
你自己编译ycm了吗？

**Comment by blueyi** [comment]
编译了的，根据打印的信息来看，应该是编译通过了的，可能是某个配置选项引起的

**Comment by tracyone** [comment]
正如我第一个回复，搜索工具我已经收集了三个，个人喜好问题，不喜欢fzf，兼容性太差，速度快不到哪里去。ale的替代品是neomake，个人喜好，觉得比ale好。

**Comment by blueyi** [comment]
嗯嗯，谢谢

**Comment by tracyone** [comment]
close
