### ISSUE TITLE
插件安装

### ISSUE THREAD

**Issue by SourceLink** [tracyone/vinux#46]
Hello tracyone:
      一直使用的你的配置进行代码浏览;
     但是最近在看go代码的时候, 在local.vim中添加如下代码:
    
    ```
    function! TVIM_user_init()
    Plug 'fatih/vim-go'
    ```
   插件链表中已经看到了vim-go安装成功, 但是无法使用vim-go中的命令. 这是为什么?

**Comment by SourceLink** [comment]
> Hello tracyone:
> 一直使用的你的配置进行代码浏览;
> 但是最近在看go代码的时候, 在local.vim中添加如下代码:
> 
> ```
> ```
> function! TVIM_user_init()
> Plug 'fatih/vim-go'
> ```
> ```
> 
> 插件链表中已经看到了vim-go安装成功, 但是无法使用vim-go中的命令. 这是为什么?

**Comment by tracyone** [comment]
解决了吗，什么问题？

**Comment by SourceLink** [comment]
已经解决了，发现只有在插件初始化函数中安装的插件才可以正常使用，其他地方安装了插件但是无法使用，不知为什么
