### ISSUE TITLE
关闭右上角提示

### ISSUE THREAD

**Issue by exten** [tracyone/vinux#73]
## Environment Information
- OS:
- vim version:
- neovim version:

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

如何关闭右上角的浮动弹框提示

**Comment by tracyone** [comment]
目前没有这个选项，而且调用这个接口的有很多处，最方便的做法就是直接修改下面这个函数：

https://github.com/tracyone/vinux/blob/master/autoload/te/utils.vim#L52
